import 'package:flutter/material.dart';

const double kMargin = 20;
const double kPadding = 20;
const kFontSize = 20;
const whiteColor = Colors.white;
const Color blackColor = Colors.black;
const Color textColor = Color(0xff686868);
const Color yellowColor = Color(0xffEFB74B);
const Color primaryColor = Color(0xffEFB74B);
const Color blueColor = Color(0xff000C66);
const Color secondaryBlue = Color(0xff189AB4);
const Color tertiaryBlue = Color(0xff75E6DA);
const Color darkBlue = Color(0xff050A30);
const Color backgroundColor = Color(0xffD4F1F4);
const Color blueBackgroundColor = Color(0xff050A30);
const Color lightBlueColor = Color(0xffD4F1F4);
const Color textBlue = Color(0xffCDD3FD);
const double KiconSize = 30;
const double kiconSize2 = 25;
const double kPadding1 = 15;
